# Generated by Django 2.2.1 on 2019-10-24 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_url', models.CharField(default='default', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MetricsDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_week', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricsTrafficModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(blank=True)),
                ('factual', models.IntegerField(blank=True)),
                ('site', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YaMetricsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='token_user')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('factual_traffic', models.ManyToManyField(related_name='factual_traffic', to='metrics.MetricsTrafficModel')),
                ('related_category', models.ManyToManyField(related_name='related_category', to='metrics.MetricsCategories')),
                ('site_traffic', models.ManyToManyField(related_name='site_traffic', to='metrics.MetricsTrafficModel')),
                ('target_traffic', models.ManyToManyField(related_name='target_traffic', to='metrics.MetricsTrafficModel')),
                ('week', models.ManyToManyField(blank=True, related_name='week', to='metrics.MetricsDateRange')),
            ],
        ),
        migrations.CreateModel(
            name='MetricsOldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('week', models.DateField()),
                ('old_factual_traffic', models.ManyToManyField(related_name='old_factual_traffic', to='metrics.MetricsTrafficModel')),
                ('old_related_category', models.ManyToManyField(related_name='old_related_category', to='metrics.MetricsCategories')),
                ('old_target_traffic', models.ManyToManyField(related_name='old_target_traffic', to='metrics.MetricsTrafficModel')),
            ],
        ),
    ]
