# Generated by Django 2.2.1 on 2019-10-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesdata',
            name='category_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='monthly_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='site_target',
            field=models.IntegerField(default=0),
        ),
    ]
