# Generated by Django 2.2.1 on 2019-10-24 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.CharField(max_length=250, null=True)),
                ('last_day', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='yametricstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metricsolddata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='metricsolddata',
            name='old_factual_traffic',
        ),
        migrations.RemoveField(
            model_name='metricsolddata',
            name='old_related_category',
        ),
        migrations.RemoveField(
            model_name='metricsolddata',
            name='old_target_traffic',
        ),
        migrations.RemoveField(
            model_name='metricsolddata',
            name='week',
        ),
        migrations.RemoveField(
            model_name='month',
            name='factual_traffic',
        ),
        migrations.RemoveField(
            model_name='month',
            name='month',
        ),
        migrations.RemoveField(
            model_name='month',
            name='related_category',
        ),
        migrations.RemoveField(
            model_name='month',
            name='site_traffic',
        ),
        migrations.RemoveField(
            model_name='month',
            name='target_traffic',
        ),
        migrations.RemoveField(
            model_name='month',
            name='week',
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_categories',
            field=models.ManyToManyField(to='metrics.MetricsCategories'),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_month_ends',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_month_starts',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_monthly_factual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_monthly_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_site_factual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_site_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsolddata',
            name='old_year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='month',
            name='categories',
            field=models.ManyToManyField(to='metrics.MetricsCategories'),
        ),
        migrations.AddField(
            model_name='month',
            name='month_ends',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='month_starts',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='monthly_factual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='monthly_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='site_factual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='site_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='metricscategories',
            name='category_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='MetricsDateRange',
        ),
        migrations.DeleteModel(
            name='MetricsTrafficModel',
        ),
        migrations.DeleteModel(
            name='YaMetricsToken',
        ),
        migrations.AddField(
            model_name='weeek',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Month'),
        ),
    ]
