# Generated by Django 2.2.1 on 2019-10-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20191024_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weeek',
            new_name='Week',
        ),
    ]
