# Generated by Django 2.2.1 on 2019-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20191024_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='is_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='week',
            name='weekly_traffic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
