# Generated by Django 2.2.1 on 2019-10-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20191029_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdLevelCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.CharField(blank=True, max_length=500, null=True)),
                ('head_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.MetricsCategories')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdLevelCategoriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.CharField(blank=True, max_length=500, null=True)),
                ('child_category_traffic', models.IntegerField(blank=True, null=True)),
                ('head_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.ThirdLevelCategories')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdLevelWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.CharField(max_length=250, null=True)),
                ('last_day', models.CharField(max_length=250, null=True)),
                ('weekly_traffic', models.IntegerField(default=0)),
                ('in_month', models.IntegerField(blank=True, null=True)),
                ('child_category_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.ThirdLevelCategoriesData')),
            ],
        ),
    ]
