# Generated by Django 2.2.1 on 2019-10-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20191024_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='category',
        ),
        migrations.AddField(
            model_name='week',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.MetricsCategories'),
        ),
    ]
