# Generated by Django 2.2.1 on 2019-10-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_thirdlevelcategories_thirdlevelcategoriesdata_thirdlevelweeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdlevelcategoriesdata',
            name='month_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.CategoriesData'),
        ),
    ]
