# Generated by Django 2.2.1 on 2019-10-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_thirdlevelcategoriesdata_month_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdlevelcategoriesdata',
            name='head_category',
        ),
    ]
