# Generated by Django 2.2.1 on 2019-10-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_auto_20191024_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.MetricsCategories'),
        ),
    ]
