# Generated by Django 2.2.1 on 2019-10-30 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_remove_thirdlevelcategoriesdata_head_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesdata',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.Month'),
        ),
        migrations.AlterField(
            model_name='metricstoken',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='head_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.MetricsCategories'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategoriesdata',
            name='month_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.CategoriesData'),
        ),
        migrations.AlterField(
            model_name='thirdlevelweeks',
            name='child_category_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.ThirdLevelCategoriesData'),
        ),
        migrations.AlterField(
            model_name='week',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.CategoriesData'),
        ),
        migrations.AlterField(
            model_name='week',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Month'),
        ),
    ]
