# Generated by Django 2.2.1 on 2019-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20191024_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='category',
        ),
        migrations.AddField(
            model_name='week',
            name='category',
            field=models.ManyToManyField(to='metrics.MetricsCategories'),
        ),
    ]
