# Generated by Django 2.2.1 on 2019-10-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20191030_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdlevelcategoriesdata',
            name='month_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_level', to='metrics.CategoriesData'),
        ),
        migrations.AlterField(
            model_name='thirdlevelweeks',
            name='child_category_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='metrics.ThirdLevelCategoriesData'),
        ),
    ]
