# Generated by Django 2.2.1 on 2019-10-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_auto_20191030_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdlevelcategoriesdata',
            name='child_category_traffic',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
