# Generated by Django 2.2.1 on 2019-10-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_auto_20191024_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricsOldData',
        ),
    ]
