# Generated by Django 2.2.1 on 2019-10-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_delete_metricsolddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='in_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
