# Generated by Django 2.2.1 on 2019-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowlerCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=240)),
                ('category_path', models.CharField(max_length=500)),
                ('category_lvl', models.IntegerField()),
                ('category_url', models.CharField(max_length=500)),
                ('parent_id', models.IntegerField()),
                ('category_title', models.TextField()),
                ('category_description', models.TextField()),
                ('category_full_name', models.TextField()),
                ('has_robots_nofollow', models.IntegerField()),
                ('has_robots_noindex', models.IntegerField()),
                ('category_canonical_url', models.CharField(max_length=500)),
                ('category_is_season', models.BooleanField()),
                ('seo_text', models.TextField()),
            ],
        ),
    ]
