# Generated by Django 2.2.1 on 2019-08-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowlercategorymodel',
            old_name='has_robots_nofollow',
            new_name='category_has_robots_nofollow',
        ),
        migrations.RenameField(
            model_name='crowlercategorymodel',
            old_name='has_robots_noindex',
            new_name='category_has_robots_noindex',
        ),
        migrations.RenameField(
            model_name='crowlercategorymodel',
            old_name='parent_id',
            new_name='category_parent_id',
        ),
        migrations.RenameField(
            model_name='crowlercategorymodel',
            old_name='seo_text',
            new_name='category_seo_text',
        ),
    ]
