# Generated by Django 2.2.1 on 2019-08-15 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0002_auto_20190815_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowlercategorymodel',
            name='category_data_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crowlercategorymodel',
            name='category_is_active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
