# Generated by Django 2.2.1 on 2019-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0003_auto_20190815_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategoryChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('old_category_name', models.CharField(max_length=240)),
                ('old_category_path', models.CharField(max_length=500)),
                ('old_category_lvl', models.IntegerField()),
                ('old_category_url', models.CharField(max_length=500)),
                ('old_category_parent_id', models.IntegerField()),
                ('old_category_title', models.TextField()),
                ('old_category_description', models.TextField()),
                ('old_category_full_name', models.TextField()),
                ('old_category_has_robots_nofollow', models.IntegerField()),
                ('old_category_has_robots_noindex', models.IntegerField()),
                ('old_category_canonical_url', models.CharField(max_length=500)),
                ('old_category_is_active', models.IntegerField()),
                ('old_category_is_season', models.BooleanField()),
                ('old_category_seo_text', models.TextField()),
                ('old_category_data_updated', models.DateTimeField()),
                ('new_category_name', models.CharField(max_length=240)),
                ('new_category_path', models.CharField(max_length=500)),
                ('new_category_lvl', models.IntegerField()),
                ('new_category_url', models.CharField(max_length=500)),
                ('new_category_parent_id', models.IntegerField()),
                ('new_category_title', models.TextField()),
                ('new_category_description', models.TextField()),
                ('new_category_full_name', models.TextField()),
                ('new_category_has_robots_nofollow', models.IntegerField()),
                ('new_category_has_robots_noindex', models.IntegerField()),
                ('new_category_canonical_url', models.CharField(max_length=500)),
                ('new_category_is_active', models.IntegerField()),
                ('new_category_is_season', models.BooleanField()),
                ('new_category_seo_text', models.TextField()),
                ('new_category_data_updated', models.DateTimeField()),
            ],
        ),
    ]
