# Generated by Django 2.2.1 on 2019-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0004_sitecategorychanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_canonical_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_full_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_has_robots_nofollow',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_has_robots_noindex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_is_active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_is_season',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_lvl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_seo_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='new_category_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_canonical_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_full_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_has_robots_nofollow',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_has_robots_noindex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_is_active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_is_season',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_lvl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_seo_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecategorychanges',
            name='old_category_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
