# Generated by Django 2.2.1 on 2019-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0007_auto_20190816_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowlerFilterPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterpage_id', models.IntegerField()),
                ('filterpage_url', models.CharField(max_length=500, null=True)),
                ('filterpage_base_url', models.CharField(max_length=500, null=True)),
                ('filterpage_title', models.TextField(null=True)),
                ('filterpage_description', models.TextField(null=True)),
                ('filterpage_text', models.TextField(null=True)),
                ('filterpage_name', models.CharField(max_length=240, null=True)),
                ('filterpage_full_name', models.TextField(null=True)),
                ('filterpage_is_active', models.IntegerField(null=True)),
                ('filterpage_disabling_reason', models.CharField(max_length=240, null=True)),
                ('filterpage_has_robots_nofollow', models.IntegerField(null=True)),
                ('filterpage_has_robots_noindex', models.IntegerField(null=True)),
                ('filterpage_canonical_url', models.CharField(max_length=500, null=True)),
                ('filterpage_is_top', models.BooleanField(null=True)),
                ('filterpage_is_active_changed_at', models.TextField(null=True)),
                ('filterpage_created_at', models.TextField(null=True)),
                ('filterpage_h1', models.TextField(null=True)),
                ('filterpage_data_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteFilterpageChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterpage_id', models.IntegerField()),
                ('old_filterpage_url', models.CharField(max_length=500, null=True)),
                ('old_filterpage_base_url', models.CharField(max_length=500, null=True)),
                ('old_filterpage_title', models.TextField(null=True)),
                ('old_filterpage_description', models.TextField(null=True)),
                ('old_filterpage_text', models.TextField(null=True)),
                ('old_filterpage_name', models.CharField(max_length=240, null=True)),
                ('old_filterpage_full_name', models.TextField(null=True)),
                ('old_filterpage_is_active', models.IntegerField(null=True)),
                ('old_filterpage_disabling_reason', models.CharField(max_length=240, null=True)),
                ('old_filterpage_has_robots_nofollow', models.IntegerField(null=True)),
                ('old_filterpage_has_robots_noindex', models.IntegerField(null=True)),
                ('old_filterpage_canonical_url', models.CharField(max_length=500, null=True)),
                ('old_filterpage_is_top', models.BooleanField(null=True)),
                ('old_filterpage_is_active_changed_at', models.TextField(null=True)),
                ('old_filterpage_created_at', models.TextField(null=True)),
                ('old_filterpage_h1', models.TextField(null=True)),
                ('new_filterpage_url', models.CharField(max_length=500, null=True)),
                ('new_filterpage_base_url', models.CharField(max_length=500, null=True)),
                ('new_filterpage_title', models.TextField(null=True)),
                ('new_filterpage_description', models.TextField(null=True)),
                ('new_filterpage_text', models.TextField(null=True)),
                ('new_filterpage_name', models.CharField(max_length=240, null=True)),
                ('new_filterpage_full_name', models.TextField(null=True)),
                ('new_filterpage_is_active', models.IntegerField(null=True)),
                ('new_filterpage_disabling_reason', models.CharField(max_length=240, null=True)),
                ('new_filterpage_has_robots_nofollow', models.IntegerField(null=True)),
                ('new_filterpage_has_robots_noindex', models.IntegerField(null=True)),
                ('new_filterpage_canonical_url', models.CharField(max_length=500, null=True)),
                ('new_filterpage_is_top', models.BooleanField(null=True)),
                ('new_filterpage_is_active_changed_at', models.TextField(null=True)),
                ('new_filterpage_created_at', models.TextField(null=True)),
                ('new_filterpage_h1', models.TextField(null=True)),
                ('new_filterpage_data_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
