# Generated by Django 2.2.1 on 2019-08-23 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowler', '0012_auto_20190823_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='is_deleted',
            field=models.ManyToManyField(related_name='is_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='is_read',
            field=models.ManyToManyField(related_name='is_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='resposive_person',
            field=models.ManyToManyField(related_name='responcive_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
