# Generated by Django 2.2.1 on 2019-08-23 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowler', '0013_auto_20190823_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='action_is',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='action_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='filterpage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='is_deleted',
            field=models.ManyToManyField(blank=True, related_name='is_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='is_read',
            field=models.ManyToManyField(blank=True, related_name='is_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='resposive_person',
            field=models.ManyToManyField(blank=True, related_name='responcive_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('responsibilities', models.ManyToManyField(to='crowler.Categories')),
            ],
        ),
    ]
