# Generated by Django 2.2.1 on 2019-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0015_auto_20190823_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='action_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
