# Generated by Django 2.2.1 on 2019-10-24 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowler', '0016_notificationmodel_action_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='resposive_person',
            field=models.ManyToManyField(blank=True, related_name='responsive_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsibilities',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, to='crowler.Categories'),
        ),
    ]
