// ДЛЯ АУТЕНТИФИКАЦИИ
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//ДЛЯ ПОДВТЕРЖДЕНИЯ МЫЛА
export const EMAIL_CONFIRMATION_REQUEST = 'EMAIL_CONFIRMATION_REQUEST'
export const EMAIL_CONFIRMATION_REQUEST_SUCCESS =
  'EMAIL_CONFIRMATION_REQUEST_SUCCESS'
export const EMAIL_CONFIRMATION_REQUEST_ERROR =
  'EMAIL_CONFIRMATION_REQUEST_ERROR'

//ДЛЯ ДОСТУПА К ЮЗЕР МОДЕЛИ
export const USER_PROFILE_GET = 'USER_PROFILE_GET'
export const USER_PROFILE_GET_SUCCESS = 'USER_PROFILE_GET_SUCCESS'
export const USER_PROFILE_GET_FAIL = 'USER_PROFILE_GET_FAIL'

//ДЛЯ КОМБИНАТОРА
export const COMBINATOR_START = 'COMBINATOR_START'
export const COMBINATOR_SUCCESS = 'COMBINATOR_SUCCESS'
export const COMBINATOR_FAIL = 'COMBINATOR_FAIL'