export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const EMAIL_CONFIRMATION_REQUEST = 'EMAIL_CONFIRMATION_REQUEST'
export const EMAIL_CONFIRMATION_REQUEST_SUCCESS =
  'EMAIL_CONFIRMATION_REQUEST_SUCCESS'
export const EMAIL_CONFIRMATION_REQUEST_ERROR =
  'EMAIL_CONFIRMATION_REQUEST_ERROR'
export const USER_PROFILE_GET = 'USER_PROFILE_GET'
export const USER_PROFILE_GET_SUCCESS = 'USER_PROFILE_GET_SUCCESS'
export const USER_PROFILE_GET_FAIL = 'USER_PROFILE_GET_FAIL'
