# Generated by Django 2.1.7 on 2019-05-29 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinatorCols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_column', models.TextField(blank=True, null=True, verbose_name='Column 1')),
                ('second_column', models.TextField(blank=True, null=True, verbose_name='Column 2')),
                ('third_column', models.TextField(blank=True, null=True, verbose_name='Column 3')),
                ('fourth_column', models.TextField(blank=True, null=True, verbose_name='Column 4')),
                ('fifth_column', models.TextField(blank=True, null=True, verbose_name='Column 5')),
                ('sixth_column', models.TextField(blank=True, null=True, verbose_name='Column 6')),
                ('seventh_column', models.TextField(blank=True, null=True, verbose_name='Column 7')),
                ('eighth_column', models.TextField(blank=True, null=True, verbose_name='Column 8')),
                ('result', models.TextField(blank=True, verbose_name='Result')),
                ('account_owner', models.CharField(default='default', max_length=250)),
                ('operation_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
